apiVersion: apps/v1
kind: Deployment
metadata:
  name: ipa2025-project-worker
  namespace: ipa2025
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ipa2025-project-worker
  template:
    metadata:
      labels:
        app: ipa2025-project-worker
        version: "v1.1"
    spec:
      containers:
        - name: ipa2025-project-worker
          image: taikie/worker:latest
          envFrom:
            - secretRef:
                name: "ipa2025-secret"
          resources:
            requests:
              cpu: "50m"
              memory: "64Mi"
            limits:
              cpu: "200m"
              memory: "256Mi"
      restartPolicy: Always
