apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: ipa2025-project-worker
  namespace: argocd
spec:
  project: ipa2025
  source:
    repoURL: 'https://github.com/multi05369/IPA-Project-IaC'
    targetRevision: HEAD
    path: worker/manifests
  destination:
    server: https://kubernetes.default.svc
    namespace: ipa2025
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
